name = "dbt-diary-reminder"
main = "worker.js"
compatibility_date = "2024-11-01"

# KV namespace id is filled in after `wrangler kv namespace create SUBS`
kv_namespaces = [
  { binding = "SUBS", id = "4b751c7ab4e740debf6fed9f7ec50d7b" }
]
